[2025-03-16T15:35:32.610+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-16T15:35:32.629+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_read_csv.execute_read_csv_task manual__2025-03-16T15:35:30.014670+00:00 [queued]>
[2025-03-16T15:35:32.641+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_read_csv.execute_read_csv_task manual__2025-03-16T15:35:30.014670+00:00 [queued]>
[2025-03-16T15:35:32.642+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-03-16T15:35:32.661+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): execute_read_csv_task> on 2025-03-16 15:35:30.014670+00:00
[2025-03-16T15:35:32.694+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=75) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-16T15:35:32.696+0000] {standard_task_runner.py:72} INFO - Started process 76 to run task
[2025-03-16T15:35:32.697+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'execute_read_csv', 'execute_read_csv_task', 'manual__2025-03-16T15:35:30.014670+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/dag_exec_csv.py', '--cfg-path', '/tmp/tmplaf3aedf']
[2025-03-16T15:35:32.699+0000] {standard_task_runner.py:105} INFO - Job 51: Subtask execute_read_csv_task
[2025-03-16T15:35:32.766+0000] {task_command.py:467} INFO - Running <TaskInstance: execute_read_csv.execute_read_csv_task manual__2025-03-16T15:35:30.014670+00:00 [running]> on host 3f0dd38626ed
[2025-03-16T15:35:32.929+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='execute_read_csv' AIRFLOW_CTX_TASK_ID='execute_read_csv_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-16T15:35:30.014670+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-16T15:35:30.014670+00:00'
[2025-03-16T15:35:32.930+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-16T15:35:33.218+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_exec_csv.py", line 14, in execute_script
    raise Exception(f"Script failed: {result.stderr}")
Exception: Script failed: Traceback (most recent call last):
  File "/opt/***/scripts/read_csv.py", line 2, in <module>
    from spark_session import spark_session
  File "/opt/***/scripts/spark_session.py", line 1, in <module>
    import findspark
ModuleNotFoundError: No module named 'findspark'

[2025-03-16T15:35:33.232+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=execute_read_csv, task_id=execute_read_csv_task, run_id=manual__2025-03-16T15:35:30.014670+00:00, execution_date=20250316T153530, start_date=20250316T153532, end_date=20250316T153533
[2025-03-16T15:35:33.357+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-16T15:35:33.358+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 51 for task execute_read_csv_task (Script failed: Traceback (most recent call last):
  File "/opt/***/scripts/read_csv.py", line 2, in <module>
    from spark_session import spark_session
  File "/opt/***/scripts/spark_session.py", line 1, in <module>
    import findspark
ModuleNotFoundError: No module named 'findspark'
; 76)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_exec_csv.py", line 14, in execute_script
    raise Exception(f"Script failed: {result.stderr}")
Exception: Script failed: Traceback (most recent call last):
  File "/opt/***/scripts/read_csv.py", line 2, in <module>
    from spark_session import spark_session
  File "/opt/***/scripts/spark_session.py", line 1, in <module>
    import findspark
ModuleNotFoundError: No module named 'findspark'

[2025-03-16T15:35:33.396+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-16T15:35:33.429+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-16T15:35:33.432+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
