[2025-03-16T14:39:33.082+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-16T14:39:33.100+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_read_csv.execute_read_csv_task manual__2025-03-16T14:39:31.973669+00:00 [queued]>
[2025-03-16T14:39:33.109+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_read_csv.execute_read_csv_task manual__2025-03-16T14:39:31.973669+00:00 [queued]>
[2025-03-16T14:39:33.110+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-03-16T14:39:33.126+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): execute_read_csv_task> on 2025-03-16 14:39:31.973669+00:00
[2025-03-16T14:39:33.157+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=662) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-16T14:39:33.160+0000] {standard_task_runner.py:72} INFO - Started process 663 to run task
[2025-03-16T14:39:33.159+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'execute_read_csv', 'execute_read_csv_task', 'manual__2025-03-16T14:39:31.973669+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/dag_exec_csv.py', '--cfg-path', '/tmp/tmpx5qzt6nf']
[2025-03-16T14:39:33.161+0000] {standard_task_runner.py:105} INFO - Job 34: Subtask execute_read_csv_task
[2025-03-16T14:39:33.221+0000] {task_command.py:467} INFO - Running <TaskInstance: execute_read_csv.execute_read_csv_task manual__2025-03-16T14:39:31.973669+00:00 [running]> on host 7e055592b66e
[2025-03-16T14:39:33.304+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='execute_read_csv' AIRFLOW_CTX_TASK_ID='execute_read_csv_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-16T14:39:31.973669+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-16T14:39:31.973669+00:00'
[2025-03-16T14:39:33.305+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-16T14:39:33.355+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_exec_csv.py", line 14, in execute_script
    raise Exception(f"Script failed: {result.stderr}")
Exception: Script failed: python: can't open file '/opt/***/E:/Airflow_Spark_Project/scripts/read_csv.py': [Errno 2] No such file or directory

[2025-03-16T14:39:33.371+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=execute_read_csv, task_id=execute_read_csv_task, run_id=manual__2025-03-16T14:39:31.973669+00:00, execution_date=20250316T143931, start_date=20250316T143933, end_date=20250316T143933
[2025-03-16T14:39:33.387+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-16T14:39:33.388+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 34 for task execute_read_csv_task (Script failed: python: can't open file '/opt/***/E:/Airflow_Spark_Project/scripts/read_csv.py': [Errno 2] No such file or directory
; 663)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_exec_csv.py", line 14, in execute_script
    raise Exception(f"Script failed: {result.stderr}")
Exception: Script failed: python: can't open file '/opt/***/E:/Airflow_Spark_Project/scripts/read_csv.py': [Errno 2] No such file or directory

[2025-03-16T14:39:33.416+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-16T14:39:33.427+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
